version: '3.1'
services:
  postgres:
    image: postgres:15.3-alpine

    container_name: postgres

    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - /.app
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  currency-bot:
    container_name: currency-bot
    image: currency-bot:latest

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update